---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-run
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: ci
  resources:
  - name: repo
    resourceRef:
      name: git-repo
