---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2022-05-23T18-45-11Z
        args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: minio123
        - name: MINIO_CONSOLE_ADDRESS
          value: "0.0.0.0:9090"
        ports:
        - containerPort: 9000
        - containerPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: minio-svc
  namespace: minio
spec:
  selector:
    app: minio
  ports:
  - protocol: TCP
    port: 9090
    nodePort: 32090
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
